### ISSUE TITLE
Invoice Fuzzy Search Component

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#736]
# Description
On the invoice view for receptionist, admin, and parent portals, there should be a fuzzy search bar to help with identifying the relevant invoice. Design is still in-progress for this, but we can lay the dev foundation first.

# Todo's
## Receptionist & Admin Portals
- [x] Search invoice by parents or invoice id. Possible inputs: "Kathy" (parent name) or "156" (invoice ID). Possible Options: Parent names and invoice ID's
- [x] The placeholder text should be "Search by Parent or Invoice ID"

## Parent Portal
- [x] Search by invoice ID. Possible inputs "156" Possible Options: Invoice ID's
- [x] The placeholder text should be "Search by Invoice ID"
