### ISSUE TITLE
Enrollment Background Tab

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#743]
# Description
Gina will hand this final design off to you, but this will display the registration information that is filled out when a student initially registers for a course including:
- Current Instructor in Class
- Current Letter Grade in Class
- Focus Area / Notes
- Textbook Used

# Todo's
- [ ] Fetch registration info from the enrollment query (need to do some research where this info is being saved)
- [ ] Create "Background" tab next to "Sessions" in the enrollment view
- [ ] Create `<EnrollmentBackground/>` component that gets displayed when the "Background" tab is clicked
- [ ] Display the data from the registration info query
