### ISSUE TITLE
Add Tutoring Sessions Flow

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#744]
# Description
The design is still pending's Gina's official handoff, but we can start laying the groundwork. 

# Background
The registration data flow uses React Redux to store registration data across several components. We'll need to update the helper functions and data structure for adding tutoring sessions. Here's the current data flow in a flow chart: 
![Screen Shot 2021-03-03 at 7 11 16 PM](https://user-images.githubusercontent.com/12959959/109905910-6647a300-7c54-11eb-868c-af88b9ab2b14.png)

# Todo's
- [ ] Update `mapRegistrationInfo()` reducer function in `registrationReducer.js`. [Read the product specs for more details](https://docs.google.com/document/d/1fD4l_RPG6tB-OwWXao0MXJ_gd0T4IPijh8YDvCoTuG4/edit#)
- [ ] Update `addTutoringSessionsRegistration()` reducer function in `registrationReducer.js`. [Read the product specs for more details](https://docs.google.com/document/d/1fD4l_RPG6tB-OwWXao0MXJ_gd0T4IPijh8YDvCoTuG4/edit#)
- [ ] Create an “addTutoringSessionsRegistration()” reducer function in registrationReducer.js to do the following:
  - Inputs: enrollmentId (ID), numSessions (integer)
  - Output: updated registration state with enrollment + numSessions. You should call on the updated mapRegistrationInfo() function you updated previously.
- [ ] Update “existingEnrollments” variable logic in PaymentBoard.js: add check for existing tutoring enrollments. If there’s an existing tutoring enrollment, we want to add it to the list of existingEnrollments.
