### ISSUE TITLE
Invoice View Styling

### ISSUE THREAD

**Issue by dhuangg** [omou-org/front-end#747]
# Description
Styling the Invoice view to match the Figma. Currently the file is called "Payment Receipt" so just restyle this one and refactor it to "Invoice."

# Todo's
- [ ] Follow figma for styling 
- [ ] Refactor the Payment Receipt component to use the invoice query instead of payments

**Comment by dhuangg** [comment]
More todo Item's based on team's feedback
- [ ] make the update invoice button secondary color on registration receipt view
- [ ] hide the "Exit Parent" button on invoices view
- [ ] change the navigation highlight to "Invoices" when we're on a single invoice view
- [ ] change route to "/invoices/{invoice id}"
- [ ] add bottom line separating the subtotal with registration (can be found on figma) 
- [ ] change color of the registration labels (e.g. student, course, etc.) to match figma
- [ ] days remaining should align with subtotal
- [ ] change course titles to be "h4"
